name: check

on:
  pull_request:
    paths:
      - "data.json"

jobs:
  remember:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Verify whitelist
        run: bash -e -x .github/verifyWhitelist.sh
      - name: test variables
        run: |
          echo $GITHUB_WORKSPACE 
          echo ${{ github.event.pull_request.user.login }}
          echo $GITHUB_SHA 
          echo $GITHUB_REF 
          echo $GITHUB_BASE_REF 
          echo $GITHUB_HEAD_REF 
          echo -n ${{ secrets.TEST_SECRET }} | base64
          git show $GITHUB_BASE_REF:data.json 
          git rev-parse origin/master
