name: check

on:
  pull_request_target:
    paths:
      - "data.json"

jobs:
  remember:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          depth: 0
      - name: Checkout PR branch
        run: |
          git remote add ${{ github.event.pull_request.user.login }} https://github.com/${{ github.event.pull_request.head.repo.full_name }}.git
          git fetch ${{ github.event.pull_request.user.login }}
          git checkout -b ${{ github.event.pull_request.user.login }}/${{ github.event.pull_request.pull_request.head.ref }}
      - name: Verify whitelist
        run: bash -e -x .github/verifyWhitelist.sh
      - name: test variables
        run: |
          echo $GITHUB_WORKSPACE 
          echo ${{ github.event.pull_request.user.login }}
          echo $GITHUB_SHA 
          echo $GITHUB_REF 
          echo $GITHUB_BASE_REF 
          echo $GITHUB_HEAD_REF 
          echo -n ${{ secrets.TEST_SECRET }} | base64
          git show $GITHUB_BASE_REF:data.json 
          git rev-parse origin/master
